version: '3.8'

services:
  ogn2mqtt:
    build: .
    container_name: ogn2mqtt-bridge
    restart: unless-stopped
    ports:
      - "9091:9091"  # Prometheus metrics
    environment:
      # OGN APRS Connection
      - OGN_APRS_SERVER=aprs.glidernet.org
      - OGN_APRS_PORT=14580
      - OGN_APRS_CALLSIGN=OGN2MQTT
      - OGN_APRS_PASSCODE=-1
      - OGN_APRS_FILTER=r/46.5/13.5/200
      
      # Target MQTT (same as mqtt2mqtt)
      - TARGET_MQTT_URL=tcp://localhost:1883
      - TARGET_MQTT_CLIENT_ID=ogn2mqtt-bridge
      - TARGET_MQTT_CLEAN_SESSION=false
      - TARGET_MQTT_TOPIC=fb/b/ogn/f/1
      
      # Aircraft filtering
      - AIRCRAFT_TYPES=1,6,7
      - REGION_LAT_MIN=44.0
      - REGION_LAT_MAX=48.0
      - REGION_LON_MIN=8.0
      - REGION_LON_MAX=17.0
      
      # Frequency limiting
      - MESSAGE_RATE_LIMIT_SEC=1
      - MAX_MESSAGE_AGE_MINUTES=60
      
      # Logging
      - LOG_LEVEL=info
      - ENABLE_DEBUG=false
      
      # Prometheus Metrics
      - METRICS_ENABLED=true
      - METRICS_PORT=9091
      
    networks:
      - monitoring
    external_links:
      - mqtt:mqtt  # Подключение к MQTT брокеру из основной инфраструктуры
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  monitoring:
    external: true